package com.cashir.blackmarketdata.util

val RUSSIAN_ID_MAP = mapOf(
    "2H_BOW" to "Лук",
    "2H_WARBOW" to "Боевой лук",
    "2H_LONGBOW" to "Длинный лук",
    "2H_LONGBOW_UNDEAD" to "Шепчущий лук",
    "2H_BOW_HELL" to "Вой Лук",
    "2H_BOW_KEEPER" to "Лук Бадона",
    "2H_BOW_AVALON" to "Туманный пронзатель",
    "2H_CROSSBOW" to "Арбалет",
    "2H_CROSSBOWLARGE" to "Тяжелый арбалет",
    "MAIN_1HCROSSBOW" to "Легкий арбалет",
    "2H_REPEATINGCROSSBOW_UNDEAD" to "Плачущий повторяющий арбалет",
    "2H_DUALCROSSBOW_HELL" to "Балкастеры",
    "2H_CROSSBOWLARGE_MORGANA" to "Осадный арбалет",
    "2H_CROSSBOW_CANNON_AVALON" to "Формирователь энергии",
    "MAIN_CURSEDSTAFF" to "Проклятый посох",
    "2H_CURSEDSTAFF" to "Большой проклятый посох",
    "2H_DEMONICSTAFF" to "Демонический посох",
    "MAIN_CURSEDSTAFF_UNDEAD" to "Посох жизненного проклятия",
    "2H_SKULLORB_HELL" to "Проклятый череп",
    "2H_CURSEDSTAFF_MORGANA" to "Посох проклятия",
    "MAIN_CURSEDSTAFF_AVALON" to "Призыватель теней",
    "MAIN_FIRESTAFF" to "Огненный посох",
    "2H_FIRESTAFF" to "Гнев",
    "2H_INFERNOSTAFF" to "Инфернальный посох",
    "MAIN_FIRESTAFF_KEEPER" to "Посох дикой природы",
    "2H_FIRESTAFF_HELL" to "Посох серного камня",
    "2H_INFERNOSTAFF_MORGANA" to "Пылающий посох",
    "2H_FIRE_RINGPAIR_AVALON" to "Утренний звон",
    "MAIN_FROSTSTAFF" to "Ледяной посох",
    "2H_FROSTSTAFF" to "Большой ледяной посох",
    "2H_GLACIALSTAFF" to "Ледниковый посох",
    "MAIN_FROSTSTAFF_KEEPER" to "Посох инея",
    "2H_ICEGAUNTLETS_HELL" to "Посох сосулек",
    "2H_ICECRYSTAL_UNDEAD" to "Призматический посох",
    "MAIN_FROSTSTAFF_AVALON" to "Ледяной зов",
    "2H_FROSTSTAFF_CRYSTAL" to "Арктический посох",
    "MAIN_ARCANESTAFF" to "Тайный посох",
    "2H_ARCANESTAFF" to "Большой тайный посох",
    "2H_ENIGMATICSTAFF" to "Загадочный посох",
    "MAIN_ARCANESTAFF_UNDEAD" to "Посох ведьмы",
    "2H_ARCANESTAFF_HELL" to "Оккультный посох",
    "2H_ENIGMATICORB_MORGANA" to "Злобный локус",
    "2H_ARCANE_RINGPAIR_AVALON" to "Вечерний звон",
    "2H_ARCANESTAFF_CRYSTAL" to "Астральный посох",
    "MAIN_HOLYSTAFF" to "Святой посох",
    "2H_HOLYSTAFF" to "Большой святой посох",
    "2H_DIVINESTAFF" to "Божественный посох",
    "MAIN_HOLYSTAFF_MORGANA" to "Посох прикосновения жизни",
    "2H_HOLYSTAFF_HELL" to "Павший посох",
    "2H_HOLYSTAFF_UNDEAD" to "Посох искупления",
    "MAIN_HOLYSTAFF_AVALON" to "Падающий свет",
    "MAIN_NATURESTAFF" to "Природный посох",
    "2H_NATURESTAFF" to "Большой природный посох",
    "2H_WILDSTAFF" to "Дикий посох",
    "MAIN_NATURESTAFF_KEEPER" to "Посох друида",
    "2H_NATURESTAFF_HELL" to "Посох гнили",
    "2H_NATURESTAFF_KEEPER" to "Неукротимый посох",
    "MAIN_NATURESTAFF_AVALON" to "Железнокорневой посох",
    "MAIN_DAGGER" to "Кинжал",
    "2H_DAGGERPAIR" to "Пара кинжалов",
    "2H_CLAWPAIR" to "Когти",
    "MAIN_RAPIER_MORGANA" to "Кровавое письмо",
    "MAIN_DAGGER_HELL" to "Демонический клык",
    "2H_IRONGAUNTLETS_HELL" to "Черные руки",
    "2H_DUALSICKLE_UNDEAD" to "Смертоносные косы",
    "2H_DAGGER_KATAR_AVALON" to "Оседланная ярость",
    "MAIN_SPEAR" to "Копье",
    "2H_SPEAR" to "Пика",
    "2H_GLAIVE" to "Глефа",
    "MAIN_SPEAR_KEEPER" to "Геронское копье",
    "2H_HARPOON_HELL" to "Охотник за духами",
    "2H_TRIDENT_UNDEAD" to "Троичный копье",
    "MAIN_SPEAR_LANCE_AVALON" to "Светоносец",
    "2H_GLAIVE_CRYSTAL" to "Расщепляющая глефа",
    "MAIN_AXE" to "Боевой топор",
    "2H_AXE" to "Рука Хора",
    "2H_HALBERD" to "Алебарда",
    "2H_HALBERD_MORGANA" to "Зов мертвецов",
    "2H_SCYTHE_HELL" to "Адская коса",
    "2H_DUALAXE_KEEPER" to "Медвежьи лапы",
    "2H_AXE_AVALON" to "Разрушитель мира",
    "2H_SCYTHE_CRYSTAL" to "Кристаллический жнец",
    "MAIN_SWORD" to "Палаш",
    "2H_CLAYMORE" to "Клеймор",
    "2H_DUALSWORD" to "Пара мечей",
    "MAIN_SCIMITAR_MORGANA" to "Кларент клинок",
    "2H_CLEAVER_HELL" to "Режущий меч",
    "2H_DUALSCIMITAR_UNDEAD" to "Пара галатинов",
    "2H_CLAYMORE_AVALON" to "Корольмейкер",
    "MAIN_SWORD_CRYSTAL" to "Клинок бесконечности",
    "2H_QUARTERSTAFF" to "Четвертной посох",
    "2H_IRONCLADEDSTAFF" to "Посох в железных доспехах",
    "2H_DOUBLEBLADEDSTAFF" to "Двулезвийный посох",
    "2H_COMBATSTAFF_MORGANA" to "Посох черного монаха",
    "2H_TWINSCYTHE_HELL" to "Коса души",
    "2H_ROCKSTAFF_KEEPER" to "Посох равновесия",
    "2H_QUARTERSTAFF_AVALON" to "Граальский искатель",
    "2H_DOUBLEBLADEDSTAFF_CRYSTAL" to "Фантомный двулезвийник",
    "MAIN_HAMMER" to "Молот",
    "2H_POLEHAMMER" to "Древковый молот",
    "2H_HAMMER" to "Большой молот",
    "2H_HAMMER_UNDEAD" to "Молот гробницы",
    "2H_DUALHAMMER_HELL" to "Кузнечные молоты",
    "2H_RAM_KEEPER" to "Хранитель рощи",
    "2H_HAMMER_AVALON" to "Рука правосудия",
    "MAIN_MACE" to "Булава",
    "2H_MACE" to "Тяжелая булава",
    "2H_FLAIL" to "Моргенштерн",
    "MAIN_ROCKMACE_KEEPER" to "Скальный молот",
    "MAIN_MACE_HELL" to "Инкубусская булава",
    "2H_MACE_MORGANA" to "Маска Камланна",
    "2H_DUALMACE_AVALON" to "Хранители клятвы",
    "2H_KNUCKLES_SET1" to "Перчатки бойца",
    "2H_KNUCKLES_SET2" to "Боевые браслеты",
    "2H_KNUCKLES_SET3" to "Шипованные перчатки",
    "2H_KNUCKLES_KEEPER" to "Медвежьи когти",
    "2H_KNUCKLES_HELL" to "Адские руки",
    "2H_KNUCKLES_MORGANA" to "Перчатки удара ворона",
    "2H_KNUCKLES_AVALON" to "Кулаки Авалона",
    "2H_SHAPESHIFTER_SET1" to "Посох охотника",
    "2H_SHAPESHIFTER_SET2" to "Посох корней",
    "2H_SHAPESHIFTER_SET3" to "Первобытный посох",
    "2H_SHAPESHIFTER_MORGANA" to "Посох кровавой луны",
    "2H_SHAPESHIFTER_HELL" to "Посох адского порождения",
    "2H_SHAPESHIFTER_KEEPER" to "Посох руны земли",
    "2H_SHAPESHIFTER_AVALON" to "Посох светлого призыва"
)