name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
     - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull front-end Docker image
        run: sudo docker pull allduiiin/black-market-data_front-end:latest
      - name: Pull back end Docker image
        run: sudo docker pull allduiiin/black-market-data_spring-app:latest

#      - name: Delete Old docker containers
#        run: sudo docker rm -f $(sudo docker ps -a -q)
      - name: Delete Old docker container
        run: sudo docker rm -f black-market-data_spring-app-container || true
      - name: Delete Old docker container
        run: sudo docker rm -f black-market-data_spring-app-container || true

      - name: Run Front end at Docker Container
        run: sudo docker run -d -p 8080:8080 --name black-market-data_spring-app-container allduiiin/black-market-data_spring-app
      - name: Run Back end at Container
        run: sudo docker run -d -p 3000:3000 --name black-market-data_front-end-container allduiiin/black-market-data_spring-app