name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
     - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull front-end Docker image
        run: sudo docker pull allduiiin/black-market-data_front-end:latest
      - name: Pull back end Docker image
        run: sudo docker pull allduiiin/black-market-data_spring-app:latest

      - name: Delete Old docker containers
        run: sudo docker rm -f $(sudo docker ps -a -q)

      - name: Run Postgre at Docker Container
        run: sudo docker run -d --name my-postgres-container -e POSTGRES_DB=mydatabase -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=myuser -p 5432:5432 postgres:latest
      - name: Run Front end at Docker Container
        run: sudo docker run -d -p 8080:8080 --name black-market-data_spring-app-container allduiiin/black-market-data_spring-app
      - name: Run Back end at Container
        run: sudo docker run -d -p 3000:3000 --name black-market-data_front-end-container allduiiin/black-market-data_spring-app