name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
     - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull allduiiin/black-market-data_front-end:latest
      - name: Delete Old docker container
        run: sudo docker rm -f black-market-data_front-end-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name black-market-data_front-end-container allduiiin/black-market-data_spring-app