name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "allduiiin"
          password: "yz8sDynAt.p3u-4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy Docker containers
        run: |
          docker-compose -f compose.yaml build
          docker tag black-market-data_spring-app allduiiin/black-market-data_spring-app:latest
          docker tag black-market-data_front-end allduiiin/black-market-data_front-end:latest
          docker push your-dockerhub-username/black-market-data_spring-app:latest
          docker push your-dockerhub-username/black-market-data_front-end:latest